version: '3.9'

services:
  redis:
    image: redis:alpine

  backend:
    build: ./backend
    ports:
      - "5000:5000"

    depends_on:
      - redis

  frontend:
    build: ./App
    environment:
      - BACKEND_URL=http://backend:5000
    ports:
      - "5173:5173"

    depends_on:
      - backend